#################
# RabbitMQ Base #
####################################################
#                                                  #
# Please keep in mind that Lando is still in Beta! #
# for overriding the settings please make a .lando #
#                                                  #
####################################################

# Name of the project
name: RabbitMQ

# Set a reachable management site ( User: guest, Pass: guest )
proxy:
    rabbitmq:
      - rabbit.lndo.site:15672

# Setup RabbitMQ service using "compose"
services:
  rabbitmq:
    type: compose
    services:
     # Grab RabbitMQ management image
     image: "rabbitmq:3-management"
     hostname: "rabbit"

     # Start the server for RabbitMQ
     command: rabbitmq-server

     # Expose RabbitMQ Ports
     ports:
      - '15672:15672'
      - '5672:5672'

     # Link RabbitMQ Configs
     volumes:
      - rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
     labels:
       NAME: "rabbitmq"
# Shows IP address on 'lando start'
events:
  post-start:
    - rabbitmq: echo -e "\n\e[36mRABBITMQ IP ADDRESS:\e[32m"
    - rabbitmq: hostname -i | cut -d' ' -f1
tooling:
  # Set up command "Lando rabbit" for basic RabbitMQ commands
  rabbit:
    service: rabbitmq
    # User must be root to prevent erlang cookie error
    user: root
    cmd: rabbitmqctl
  # Setup command "lando rabbit-ip" to get the ip address
  rabbit-ip:
    service: rabbitmq
    cmd:    
      - echo -e "\n\e[36mRABBITMQ IP ADDRESS:\e[32m"
      - hostname -i | cut -d' ' -f1
